language: php

php:
  - 7.0
  - hhvm
  - nightly

before_script:
  ## Composer
  - composer self-update
  - composer install --prefer-source --no-interaction --dev  --ignore-platform-reqs

script: phpunit

matrix:
  allow_failures:
    - php:
        - hhvm
        - nightly

sudo: false
